site_name: Beyah Solutions
docs_dir: src
plugins:
  - blog
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
# extra:
#   social:
#     - type: 'github'
#       link: 'https://github.com/beyahsolutions'
google_analytics:
  - 'UA-69987010-1'
  - auto
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
use_directory_urls: false
nav:
  - About: index.md
  - Blog: blog/index.md
